@startuml
start

:Select Replication Strategy to Check;

:Retrieve details of Replication Strategy;

:Display Sync Checker Configuration;

:Select Time Interval for Analysis;

: Validate Sync Check configuration;

if (Valid Sync Check) then (true)
  :Create Sync Checker;
else (false)
  :Display Error message;
endif

:On selected Time Period Compare Source and Target Database Data;
if (Data Discrepancies Found) then (true)
  :Identify Discrepancy Details (Tables, Rows, Data Values);
  :Generate Discrepancy Report;
  :Notify Administrators;
else (false)
  :Generate Sync Success Report;
endif

stop
@enduml