@startuml

abstract class Database {
  - databaseType: String
  - connectionString: String
  - password: String
  - configuration: String
  - size: int
  - status: String
  - lastUpdated: Date
}

abstract class DatabaseType{
  + getDescription(): String
}

class NoSQL extends DatabaseType {

}

class SQL extends DatabaseType {

}

class MongoDB extends NoSQL {
  - replicaSet: String
}

class CouchDB extends NoSQL {
  - designDocuments: DesignDocument[]
}

class H2 extends SQL {
  - mode: String
}

class SQLite extends SQL {
  - filePath: String
}

class Connection {
  - connectionType: String
  - startDB: Database
  - endDB: Database
  - status: String
  - lastUsed: Date
}

abstract class ReplicationStrategy {
    - name : String
    - syncInterval: int
    - terminationProtocol : TerminationProtocol
}

class UniDirectionalReplication extends ReplicationStrategy {
  - tables: Table[]
  - replicationStrategy: ReplicationStrategy

}

class Federation extends ReplicationStrategy {
  - databases: Database []
  - tables: Table[]
  - replicationStrategy: ReplicationStrategy
  - syncInterval: int
  - terminationProtocol : TerminationProtocol
}

class BiDirectionalReplication extends ReplicationStrategy {
  - tables: Table[]
  - replicationStrategy: ReplicationStrategy
  - syncInterval: int
  - terminationProtocol : TerminationProtocol
}

class Database_System {
  - databases: Database[]
  - connections: Connection[]
  + addConnection(connection: Connection)
  + addDatabase(database: Database)
  - monitorDatabases(): void
}

abstract class SyncChecker {
  + checkSyncStatus(): void
}

class UniDirectionalSyncChecker extends SyncChecker {

}

class BiDirectionalSyncChecker extends SyncChecker {

}

class FederationSyncChecker extends SyncChecker {

}

Database <|-- DatabaseType
Connection "1" -- "0…*" ReplicationStrategy
Connection "1" -- "1" SyncChecker
Connection "1…*" -- "2…*" Database

Database_System "1" -- "*" Database

Database_System "1" -- "*" Connection

@enduml